import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import test from "node:test";
import { join } from "node:path";
import {
  TASK_PAYLOAD_FIELDS,
  TASK_RESULT_FIELDS,
  createTaskPayload,
  createTaskResult,
  parseTaskPayload,
  parseTaskResult,
} from "../src/ipc.js";

function verifyPythonParsing(className: string, jsonData: any): any {
  const script = `
import sys, json
sys.path.insert(0, ".")
from scripts.task_runner import ${className}
try:
    data = json.loads(sys.argv[1])
    obj = ${className}.from_dict(data)
    print(json.dumps({"status": "ok", "id": obj.id}))
except Exception as e:
    print(json.dumps({"status": "error", "message": str(e)}))
`;
  const out = execFileSync("python3", ["-c", script, JSON.stringify(jsonData)], {
    encoding: "utf-8",
    cwd: process.cwd(),
  });
  return JSON.parse(out.trim());
}

test("IPC Protocol - Wave 5: Semantic Alignment", async (t) => {

  await t.test("TaskPayload generated by TS should be parsed by Python", () => {
    const payload = createTaskPayload({
      id: "test-task-1",
      prompt: "hello AST",
      mode: "text",
      timestamp: new Date().toISOString(),
      system: "You are an assistant",
      round: 2
    });

    const pyResult = verifyPythonParsing("TaskPayload", payload);
    assert.equal(pyResult.status, "ok", `Python failed to parse TS payload: ${pyResult.message}`);
    assert.equal(pyResult.id, "test-task-1");
  });

  await t.test("Python should REJECT payload missing required fields (P1 strictness)", () => {
    const brokenPayload = { id: "bad", timestamp: "now" }; // Missing prompt and mode
    const pyResult = verifyPythonParsing("TaskPayload", brokenPayload);
    assert.equal(pyResult.status, "error");
    assert.match(pyResult.message, /missing required fields/i);
  });

  await t.test("TS Schema should contain all Wave 5 fields", () => {
    assert.ok(TASK_PAYLOAD_FIELDS.includes("system"), "Should have system field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("staticContext"), "Should have staticContext field");
    assert.ok(TASK_RESULT_FIELDS.includes("changes"), "Should have changes field");
  });

  await t.test("createTaskResult should produce valid result", () => {
    const result = createTaskResult({
      id: "res-1",
      status: "success",
      content: "done"
    });
    const parsed = parseTaskResult(result);
    assert.equal(parsed.id, "res-1");
    assert.equal(parsed.status, "success");
  });
});
