import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import test from "node:test";
import { join } from "node:path";
import {
  TASK_PAYLOAD_FIELDS,
  TASK_PAYLOAD_SCHEMA_VERSION,
  TASK_RESULT_FIELDS,
  createTaskPayload,
  createTaskResult,
  parseTaskPayload,
  parseTaskResult,
} from "../src/ipc.js";

function verifyPythonParsing(className: string, jsonData: any): any {
  const script = `
import sys, json
sys.path.insert(0, ".")
from scripts.task_runner import ${className}
try:
    data = json.loads(sys.argv[1])
    obj = ${className}.from_dict(data)
    print(json.dumps({"status": "ok", "id": obj.id}))
except Exception as e:
    print(json.dumps({"status": "error", "message": str(e)}))
`;
  const out = execFileSync("python3", ["-c", script, JSON.stringify(jsonData)], {
    encoding: "utf-8",
    cwd: process.cwd(),
  });
  return JSON.parse(out.trim());
}

test("IPC Protocol - Wave 5 / Phase D: TaskPayload alignment", async (t) => {

  await t.test("TaskPayload generated by TS should be parsed by Python", () => {
    const payload = createTaskPayload({
      id: "test-task-1",
      prompt: "hello AST",
      mode: "text",
      timestamp: new Date().toISOString(),
      system: "You are an assistant",
      round: 2
    });

    const pyResult = verifyPythonParsing("TaskPayload", payload);
    assert.equal(pyResult.status, "ok", `Python failed to parse TS payload: ${pyResult.message}`);
    assert.equal(pyResult.id, "test-task-1");
  });

  await t.test("Python should REJECT payload missing required fields (P1 strictness)", () => {
    const brokenPayload = { id: "bad", timestamp: "now" }; // Missing prompt and mode
    const pyResult = verifyPythonParsing("TaskPayload", brokenPayload);
    assert.equal(pyResult.status, "error");
    assert.match(pyResult.message, /missing required fields/i);
  });

  await t.test("TS Schema should contain Wave 5 and Phase D payload fields", () => {
    assert.ok(TASK_PAYLOAD_FIELDS.includes("system"), "Should have system field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("staticContext"), "Should have staticContext field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("agentId"), "Should have agentId field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("parentHandoffId"), "Should have parentHandoffId field");
    assert.ok(TASK_RESULT_FIELDS.includes("changes"), "Should have changes field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("delegateArgv"), "Should have delegateArgv field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("finalizeStrategy"), "Should have finalizeStrategy field");
    assert.ok(TASK_PAYLOAD_FIELDS.includes("sharedLockKey"), "Should have sharedLockKey field");
    assert.ok(TASK_RESULT_FIELDS.includes("workspacePath"), "Should have workspacePath field");
    assert.ok(TASK_RESULT_FIELDS.includes("workspaceRepoRoot"), "Should have workspaceRepoRoot field");
    assert.ok(TASK_RESULT_FIELDS.includes("workspaceBaseRef"), "Should have workspaceBaseRef field");
    assert.ok(TASK_RESULT_FIELDS.includes("workspaceSharedLockKey"), "Should have workspaceSharedLockKey field");
  });

  await t.test("parseTaskPayload accepts defer finalize and shared lock key", () => {
    const parsed = parseTaskPayload({
      id: "defer-1",
      prompt: "p",
      mode: "agent-write",
      timestamp: new Date().toISOString(),
      schemaVersion: TASK_PAYLOAD_SCHEMA_VERSION,
      finalizeStrategy: "defer",
      sharedLockKey: "trace-123",
    });
    assert.equal(parsed.finalizeStrategy, "defer");
    assert.equal(parsed.sharedLockKey, "trace-123");
  });

  await t.test("parseTaskPayload accepts optional multi-agent fields and current schemaVersion", () => {
    const parsed = parseTaskPayload({
      id: "ma-1",
      prompt: "p",
      mode: "text",
      timestamp: new Date().toISOString(),
      schemaVersion: TASK_PAYLOAD_SCHEMA_VERSION,
      agentId: "agent-a",
      parentHandoffId: "handoff-001",
    });
    assert.equal(parsed.agentId, "agent-a");
    assert.equal(parsed.parentHandoffId, "handoff-001");
    assert.equal(parsed.schemaVersion, TASK_PAYLOAD_SCHEMA_VERSION);
  });

  await t.test("parseTaskPayload rejects newer-than-supported schemaVersion", () => {
    assert.throws(
      () =>
        parseTaskPayload({
          id: "x",
          prompt: "p",
          mode: "text",
          timestamp: "t",
          schemaVersion: TASK_PAYLOAD_SCHEMA_VERSION + 1,
        }),
      /newer than supported/i
    );
  });

  await t.test("TaskPayload with Phase D fields and legacy schemaVersion 5 parses in Python", () => {
    const payload = {
      id: "legacy-5",
      prompt: "hello",
      mode: "text",
      timestamp: new Date().toISOString(),
      schemaVersion: 5,
      agentId: "sub",
      parentHandoffId: "ph-1",
    };
    const pyResult = verifyPythonParsing("TaskPayload", payload);
    assert.equal(pyResult.status, "ok", pyResult.message);
    assert.equal(pyResult.id, "legacy-5");
  });

  await t.test("Python rejects TaskPayload with invalid mode string", () => {
    const bad = {
      id: "bad-mode",
      prompt: "p",
      mode: "agent-readonly",
      timestamp: new Date().toISOString(),
      schemaVersion: TASK_PAYLOAD_SCHEMA_VERSION,
    };
    const pyResult = verifyPythonParsing("TaskPayload", bad);
    assert.equal(pyResult.status, "error");
    assert.match(pyResult.message, /mode must be one of/i);
  });

  await t.test("Python rejects TaskPayload with unsupported future schemaVersion", () => {
    const bad = {
      id: "future",
      prompt: "p",
      mode: "text",
      timestamp: "t",
      schemaVersion: TASK_PAYLOAD_SCHEMA_VERSION + 9,
    };
    const pyResult = verifyPythonParsing("TaskPayload", bad);
    assert.equal(pyResult.status, "error");
    assert.match(pyResult.message, /newer than supported/i);
  });

  await t.test("createTaskResult should produce valid result", () => {
    const result = createTaskResult({
      id: "res-1",
      status: "success",
      content: "done"
    });
    const parsed = parseTaskResult(result);
    assert.equal(parsed.id, "res-1");
    assert.equal(parsed.status, "success");
  });

  await t.test("parseTaskResult accepts workspace metadata", () => {
    const result = parseTaskResult({
      id: "agent-res-1",
      status: "success",
      usage: { promptTokens: 1, completionTokens: 2 },
      schemaVersion: 5,
      summary: "done",
      workspacePath: "/tmp/ws-1",
      workspaceRepoRoot: "/tmp/repo",
      workspaceBaseRef: "abc123",
      workspaceSharedLockKey: "trace-123",
      filesModified: ["a.ts"],
    });
    assert.equal(result.workspacePath, "/tmp/ws-1");
    assert.equal(result.workspaceRepoRoot, "/tmp/repo");
    assert.equal(result.workspaceBaseRef, "abc123");
    assert.equal(result.workspaceSharedLockKey, "trace-123");
    assert.deepEqual(result.filesModified, ["a.ts"]);
  });
});
